#!/bib/bash
limit_attempts=4
attempts=$(grep "failure" /var/log/auth.log | wc -l)
if [ "$attempts" -ge "$limit_attempts" ]; then
  echo "Possible brute force attack"
else
  echo "No activity detected"
fi
