#!/bin/bash
limit_attempts=3
attempts=$(grep "failure" /var/log/auth.log | wc -l)
echo "Number of attempts" $attempts
cat /var/log/auth.log | grep "failure"
if [ "$attempts" -ge "$limit_attempts" ]; then
notify-send --icon=utilities.terminal "ALERT" "Possible brute force attack"
else
notify-send --icon=utilities-terminal "ALERT" "No activity detected"
fi
