#!/bin/bash
log_file="/var/log/auth.log"
limit_attempts=4
attempts=$(egrep "Failed Password | incorrect password" | wc -l)
if ["$attempts" -ge "$limit_attempts"]; then
  echo "Possible brute force attack"
else
  echo "No activity detected"
fi
